In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf

In [23]:

def get_data(days,tikers):
    df = pd.DataFrame()
    for company in tickers.keys():
        tkr = yf.Ticker(tickers[company])
        hist = tkr.history(period=f'{days}d')
        hist.index = hist.index.strftime("%d %B %Y")
        hist = hist[["Close"]]
        hist.columns = [company]
        hist = hist.T
        hist.index.name = "Name"
        df.append(hist)
        df = pd.concat([df,hist])
    return df

In [24]:
tickers = {
    "apple":"AAPL",
    "facebook":"FB",
    "google":"GOOGL",
    "microsoft":"MSFT",
    "netflix":"NFLX",
    "amazon":"AMZN"
}
days = 50
get_data(days,tickers)

Date,06 October 2021,07 October 2021,08 October 2021,11 October 2021,12 October 2021,13 October 2021,14 October 2021,15 October 2021,18 October 2021,19 October 2021,...,02 December 2021,03 December 2021,06 December 2021,07 December 2021,08 December 2021,09 December 2021,10 December 2021,13 December 2021,14 December 2021,15 December 2021
Name,,,,,,,,,,,,,,,,,,,,,
apple,141.793060,143.081177,142.691742,142.601883,141.303772,140.704651,143.550491,144.628922,146.336426,148.543198,...,163.759995,161.839996,165.320007,171.179993,175.080002,174.559998,179.449997,175.740005,174.330002,179.300003
facebook,333.640015,329.220001,330.049988,325.450012,323.769989,324.540009,328.529999,324.760010,335.339996,339.989990,...,310.390015,306.839996,317.869995,322.809998,330.559998,329.820007,329.750000,334.489990,333.739990,341.660004
google,2751.300049,2784.500000,2795.709961,2778.280029,2728.979980,2751.639893,2823.020020,2827.360107,2855.560059,2864.739990,...,2859.320068,2840.030029,2863.100098,2945.389893,2963.729980,2952.770020,2960.030029,2916.530029,2878.139893,2928.820068
microsoft,292.574707,294.311554,294.311554,293.692688,292.345154,295.768890,302.197113,303.654449,306.728851,307.667145,...,329.489990,323.010010,326.190002,334.920013,334.970001,333.100006,342.540009,339.399994,328.339996,334.649994
netflix,639.099976,631.849976,632.659973,627.039978,624.940002,629.760010,633.799988,628.289978,637.969971,639.000000,...,616.469971,602.130005,612.690002,625.580017,628.080017,611.000000,611.659973,604.559998,597.989990,605.039978
amazon,3262.010010,3302.429932,3288.620117,3246.300049,3247.330078,3284.280029,3299.860107,3409.020020,3446.739990,3444.149902,...,3437.360107,3389.790039,3427.370117,3523.290039,3523.159912,3483.419922,3444.239990,3391.350098,3381.830078,3466.300049

In [18]:
import altair as alt

In [48]:
data = get_data(days,tickers)

In [49]:
companies = ["apple","facebook"]
data = data.loc[companies]
data

Date,06 October 2021,07 October 2021,08 October 2021,11 October 2021,12 October 2021,13 October 2021,14 October 2021,15 October 2021,18 October 2021,19 October 2021,...,02 December 2021,03 December 2021,06 December 2021,07 December 2021,08 December 2021,09 December 2021,10 December 2021,13 December 2021,14 December 2021,15 December 2021
Name,,,,,,,,,,,,,,,,,,,,,
apple,141.793060,143.081177,142.691742,142.601883,141.303772,140.704651,143.550491,144.628922,146.336426,148.543198,...,163.759995,161.839996,165.320007,171.179993,175.080002,174.559998,179.449997,175.740005,174.330002,179.300003
facebook,333.640015,329.220001,330.049988,325.450012,323.769989,324.540009,328.529999,324.760010,335.339996,339.989990,...,310.390015,306.839996,317.869995,322.809998,330.559998,329.820007,329.750000,334.489990,333.739990,341.660004

In [50]:
data = data.T.reset_index()

In [51]:
data.head()

Name             Date       apple    facebook
0     06 October 2021  141.793060  333.640015
1     07 October 2021  143.081177  329.220001
2     08 October 2021  142.691742  330.049988
3     11 October 2021  142.601883  325.450012
4     12 October 2021  141.303772  323.769989

In [52]:
data = pd.melt(data,id_vars=["Date"]).rename(
    columns ={"value":"Stock Prices(USD)"}
)
data.head()

              Date   Name  Stock Prices(USD)
0  06 October 2021  apple         141.793060
1  07 October 2021  apple         143.081177
2  08 October 2021  apple         142.691742
3  11 October 2021  apple         142.601883
4  12 October 2021  apple         141.303772

In [68]:
ymin,ymax = 300,350
chart = (
    alt.Chart(data)
    .mark_line(opacity=0.7,clip = True)
    .encode(
        x = "Date:T",
        y = alt.Y("Stock Prices(USD):Q",stack = None,scale = alt.Scale(domain=[ymin,ymax])),
        color = "Name:N"
    )
)

In [69]:
chart

alt.Chart(...)